name: Build Canonical Reference

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build canonical document
        run: |
          python scripts/build_canonical.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: referentiel-canonique
          path: artifacts/
      - name: Commit generated file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add compiled/

          git diff --staged --quiet || git commit -m "Mise à jour du document canonique"

          git push
